/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Algebraica;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mensaje = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alfa = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        remplazo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BINA = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        binAn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        binCor = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        redon = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TasaCom = new javax.swing.JLabel();
        simular = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Codificación Algebraica Modificada");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel2.setText("Mensaje: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 111, -1, -1));

        mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensajeActionPerformed(evt);
            }
        });
        getContentPane().add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 112, 202, -1));

        alfa.setColumns(20);
        alfa.setRows(5);
        jScrollPane1.setViewportView(alfa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 110, 180));

        jLabel3.setText("Alfabeto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));

        jLabel4.setText("Remplazo Mensaje:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 160, -1, -1));

        remplazo.setText("0");
        getContentPane().add(remplazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 160, 220, -1));

        jLabel6.setText("Numero Binario Original:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 203, -1, -1));

        BINA.setText("0");
        getContentPane().add(BINA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 203, 430, -1));

        jLabel8.setText("Valor anterior:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 257, -1, -1));

        binAn.setText("0");
        getContentPane().add(binAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 257, 259, -1));

        jLabel10.setText("Valor del corte:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 305, -1, -1));

        binCor.setText("0");
        getContentPane().add(binCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 305, 488, -1));

        jLabel12.setText("Valor del numero para redondiar:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 350, 190, 20));

        redon.setText("0");
        getContentPane().add(redon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 380, 20));

        jLabel7.setText("Tasa de Compresión:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        TasaCom.setText("0");
        getContentPane().add(TasaCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 280, -1));

        simular.setText("Simular");
        simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simularActionPerformed(evt);
            }
        });
        getContentPane().add(simular, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 111, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenBlanco.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mensajeActionPerformed

    private void simularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simularActionPerformed
        
        String mensaje1 = mensaje.getText();
        alfa.setText("");
        if (mensaje1.length() < 5 || mensaje1.length() > 10) {
            if (mensaje1.length() < 5) {
                JOptionPane.showMessageDialog(this, "El mensaje debe ser mayor o igual a 5 caracteres");
            } else {
                JOptionPane.showMessageDialog(this, "El mensaje debe tener máximo 10 caracteres");
            }
        }else{
            char mensaje2[] = mensaje1.toCharArray();
            ArrayList<pareja> alfabeto = new ArrayList<pareja>();
            
            char mensaje3[] = mensaje1.toCharArray();
            
            int n = 0;

            for (int i = 0; i < mensaje2.length; i++) {
                if (mensaje2[i] != '*') {
                    for (int j = i + 1; j < mensaje2.length; j++) {
                        if (mensaje2[i] == mensaje2[j]) {
                            mensaje2[j] = '*';
                        }
                    }
                    alfabeto.add(new pareja(mensaje2[i], n));
                    n+= 1;
                }
            }
            if(n < 2 && n > 11){
                JOptionPane.showMessageDialog(this, "El mensaje debe por lo menos de 3 a 9 caracteres unicos");
            }else{
                System.out.println(alfabeto);
                int base = n;
                String Remplazo = "0.";
                for(int i =0; i<mensaje3.length; i++){
                    for(int j=0; j<alfabeto.size(); j++){
                        if(mensaje3[i] == alfabeto.get(j).getCaracter()){
                            Remplazo+= (int)(alfabeto.get(j).getProba()) + "";
                        } 
                    }
                }
                //imprimir alfabeto en pantalla
                for(int i=0; i<alfabeto.size(); i++){
                    alfa.append(alfabeto.get(i).getCaracter() + " = " + (int)(alfabeto.get(i).getProba()) + "\n");
                }
                System.out.println(Remplazo);
                //Imprimir el remplazo del mensaje
                remplazo.setText(Remplazo);
                base10(Remplazo, base);
                binario(base10(Remplazo, base));
                String binario1= binario(base10(Remplazo, base));
                //Imprimir el binario original
                BINA.setText(binario1);
                
                
                int x=0;
                String corte="";
                String comparacion="";
                boolean stop= false;

                while (true){
                    int contadora = 2;
                    corte="";
                    String anterior= comparacion;
                    char corte1[] = binario1.toCharArray();
                    char original[] = Remplazo.toCharArray();
                    for(int i=0; i<x; i++){
                        corte+= corte1[i] + "";
                    }
                    comparacion=baseDiferente(base10(corte,2),base, original.length);
                    char corte2[] = comparacion.toCharArray();
                    
                    System.out.println(corte);
                    System.out.println(comparacion);
                    
                    for(int i=2; i<original.length; i++){
                        System.out.println(Character.getNumericValue(original[i]));
                        System.out.println(Character.getNumericValue(corte2[i]));
                        if(Character.getNumericValue(original[i])  == Character.getNumericValue(corte2[i])){
                            contadora+=1;
                        }                       
                    }
                    System.out.println(contadora);
                    
                    if(contadora == original.length){
                        binAn.setText(anterior);
                        binCor.setText(comparacion + " / " +corte);
                        break;
                    }else{
                        x+= 1;
                    }                   
                }
                tasaCompresion(mensaje1, corte);
            }
            
        }
        
        
        
    }//GEN-LAST:event_simularActionPerformed

    public double base10(String numero, int base){
        char mensaje2[] = numero.toCharArray();
        int n=1;
        double conv=0;        
           for(int i=2; i<mensaje2.length; i++){
               conv+= Character.getNumericValue(mensaje2[i])*Math.pow(base,n*-1);   
               n+=1;
           }
           return conv;
    }
    public String binario(double numero){
        String binario ="0.";
        double a=0;
        double parteEntera=0;
        double parteDecimal=0;
        for(int i=0; i<50; i++){
            a= numero*2;
            parteDecimal= a % 1;
            parteEntera =a - parteDecimal;
            binario+= (int)(parteEntera)+"";
            numero= parteDecimal;
        }
        System.out.println(binario);
        
        return binario;
    }
    
    public String baseDiferente(double numero, int base, int tamaño){
        String numBase ="0.";
        double a=0;
        double parteEntera=0;
        double parteDecimal=0;
        for(int i=2; i<tamaño; i++){
            a= numero*base;
            parteDecimal= a % 1;
            parteEntera =a - parteDecimal;
            if(i==tamaño-1){
                if(parteDecimal > 0.5){
                    numBase+= (int) (parteEntera+1);
                }else{
                    numBase+=(int)(parteEntera)+"";
                }
            }else{
                numBase+= (int)(parteEntera)+"";
                numero= parteDecimal;
            } 
        }
        System.out.println(a);
        redon.setText(a + "");
        
        return numBase;
    }
    
    public void tasaCompresion(String mensaje, String corte){
        char mensaje1[]=mensaje.toCharArray();
        char corte1[]= corte.toCharArray();
        
        System.out.println(mensaje1.length);
        System.out.println(corte1.length);
        
        double parte1=((mensaje1.length*8-(corte1.length-2)));
        double parte2=(mensaje1.length*8);
        double tasa=(parte1/parte2)*100;
        TasaCom.setText(tasa+"");
        System.out.println("TASA= "+tasa);
        
        //Tasa.setText(tasa+"");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BINA;
    private javax.swing.JLabel TasaCom;
    private javax.swing.JTextArea alfa;
    private javax.swing.JLabel binAn;
    private javax.swing.JLabel binCor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mensaje;
    private javax.swing.JLabel redon;
    private javax.swing.JLabel remplazo;
    private javax.swing.JButton simular;
    // End of variables declaration//GEN-END:variables
}
