/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diego
 */
import java.awt.Graphics;
import java.awt.Color;
import javax.swing.JOptionPane;

public class PRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    int estadoAnterior = 0;

    public PRINCIPAL() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NumBin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MILLER = new javax.swing.JButton();
        MLT3 = new javax.swing.JButton();
        CMI = new javax.swing.JButton();
        EstArriba = new javax.swing.JButton();
        EstaAbajo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Codificación En Linea");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 27, -1, -1));

        NumBin.setText("0");
        NumBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumBinActionPerformed(evt);
            }
        });
        getContentPane().add(NumBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 120, 264, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Digite Codigo Bin:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));

        MILLER.setText("MILLER");
        MILLER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MILLERActionPerformed(evt);
            }
        });
        getContentPane().add(MILLER, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 235, 75, -1));

        MLT3.setText("MLT-3");
        MLT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLT3ActionPerformed(evt);
            }
        });
        getContentPane().add(MLT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 235, 77, -1));

        CMI.setText("CMI");
        CMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMIActionPerformed(evt);
            }
        });
        getContentPane().add(CMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1397, 235, 75, -1));

        EstArriba.setText("Arriba");
        EstArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstArribaActionPerformed(evt);
            }
        });
        getContentPane().add(EstArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, -1, -1));

        EstaAbajo.setText("Abajo");
        EstaAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstaAbajoActionPerformed(evt);
            }
        });
        getContentPane().add(EstaAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 161, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Elige Ultimo Estado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 118, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mesa de trabajo 1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumBinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumBinActionPerformed

    private void MILLERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MILLERActionPerformed

        Graphics g = getGraphics();
        fondo();
        String tramaF = NumBin.getText() + " ";
        char[] numero = tramaF.toCharArray();
        int estAn = estadoAnterior;
        int x = 60;
        int y = 0;
        g.setColor(Color.BLUE);
        for (int i = 0; i < numero.length-1; i++) {
            int actual = Character.getNumericValue(numero[i]);
            int estaF = Character.getNumericValue(numero[i + 1]);
            if (actual == 1 || actual == 0) {
                if (actual == 1) {
                    if (estAn == 1) {
                        g.drawLine(x, 500, (x + 45), 500);
                        g.drawLine((x + 45), 500, (x + 45), 700);
                        g.drawLine((x + 45), 700, (x + 90), 700);
                        estAn = -1;
                    } else {
                        g.drawLine(x, 700, (x + 45), 700);
                        g.drawLine((x + 45), 700, (x + 45), 500);
                        g.drawLine((x + 45), 500, (x + 90), 500);
                        estAn = 1;
                    }
                } else {
                    if (estaF == 0) {
                        if (estAn == 1) {
                            g.drawLine(x, 500, (x + 90), 500);
                            estAn = -1;
                        } else {
                            g.drawLine(x, 700, (x + 90), 700);
                            estAn = +1;
                        }
                        g.drawLine((x + 90), 500, (x + 90), 700);
                    } else {
                        if (estAn == 1) {
                            g.drawLine(x, 500, (x + 90), 500);
                        } else {
                            g.drawLine(x, 700, (x + 90), 700);

                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "No es un número valido");
                fondo();
                i = numero.length;
            }
            x += 90;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_MILLERActionPerformed

    private void CMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMIActionPerformed

        Graphics g = getGraphics();
        fondo();
        char[] numero = NumBin.getText().toCharArray();
        int estAn = estadoAnterior;
        int x = 60;
        g.setColor(Color.BLUE);
        for (int i = 0; i < numero.length; i++) {
            int actual = Character.getNumericValue(numero[i]);

            if (actual == 1 || actual == 0) {
                if (actual == 0) {
                    g.drawLine(x, 700, (x + 45), 700);
                    g.drawLine((x + 45), 700, (x + 45), 500);
                    g.drawLine((x + 45), 500, (x + 90), 500);
                } else if (actual == 1 && estAn == 1) {
                    g.drawLine(x, 700, (x + 90), 700);
                    estAn = -1;
                } else if (actual == 1 && estAn == -1) {
                    g.drawLine(x, 500, (x + 90), 500);
                    estAn = 1;
                }
            } else {
                JOptionPane.showMessageDialog(this, "No es un número valido");
                fondo();
                i = numero.length;
            }
            x += 90;
        }
    }//GEN-LAST:event_CMIActionPerformed

    private void EstaAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstaAbajoActionPerformed

        estadoAnterior = -1;

        // TODO add your handling code here:
    }//GEN-LAST:event_EstaAbajoActionPerformed

    private void MLT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLT3ActionPerformed

        Graphics g = getGraphics();
        fondo();
        char[] numero = NumBin.getText().toCharArray();
        int estAn = estadoAnterior;
        int esta = 0;
        int x = 60;
        int y = 600;

        g.setColor(Color.BLUE);

        for (int i = 0; i < numero.length; i++) {
            int actual = Character.getNumericValue(numero[i]);
            if (actual == 1 || actual == 0) {
                if (actual == 0) {
                    g.drawLine(x, y, (x + 90), y);
                    x += 90;
                } else {
                    if (estAn == 1 && esta == 0) {
                        g.drawLine(x, y, x, (y + 100));
                        g.drawLine(x, (y + 100), (x + 90), (y + 100));
                        y += 100;
                        x += 90;
                        estAn = 0;
                        esta = -1;
                    } else if (estAn == 0 && esta == -1) {
                        g.drawLine(x, y, x, (y - 100));
                        g.drawLine(x, (y - 100), (x + 90), (y - 100));
                        y -= 100;
                        x += 90;
                        estAn = -1;
                        esta = 0;
                    } else if (esta == 0 && estAn == -1) {
                        g.drawLine(x, y, x, (y - 100));
                        g.drawLine(x, (y - 100), (x + 90), (y - 100));
                        y -= 100;
                        x += 90;
                        estAn = 0;
                        esta = 1;
                    } else if (esta == 1 && estAn == 0) {
                        g.drawLine(x, y, x, (y + 100));
                        g.drawLine(x, (y + 100), (x + 90), (y + 100));
                        y += 100;
                        x += 90;
                        estAn = 1;
                        esta = 0;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "No es un número valido");
                fondo();
                i = numero.length;
            }

        }
    }//GEN-LAST:event_MLT3ActionPerformed


    private void EstArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstArribaActionPerformed

        estadoAnterior = 1;

        // TODO add your handling code here:
    }//GEN-LAST:event_EstArribaActionPerformed

    public void fondo() {
        int f = 60;
        Graphics g = getGraphics();
        super.paintComponents(g);
        g.setColor(Color.RED);
        g.drawLine(60, 600, 1500, 600);
        g.setColor(Color.BLACK);
        for (int i = 0; i < 16; i++) {
            g.drawLine(f, 450, f, 750);
            f += 90;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CMI;
    private javax.swing.JButton EstArriba;
    private javax.swing.JButton EstaAbajo;
    private javax.swing.JButton MILLER;
    private javax.swing.JButton MLT3;
    private javax.swing.JTextField NumBin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
